Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,19 +31,19 @@ jobs:
 
       - name: Create RDP User with Secure Password
         run: |
-           $password = "rdp123"
-            $securePass = ConvertTo-SecureString $password -AsPlainText -Force
+          $password = "rdp123"
+          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
+          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
+          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
+          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
+    
+          echo "RDP_CREDS=User: RDP | Password: $password" >> $env:GITHUB_ENV
+    
+          if (-not (Get-LocalUser -Name "RDP")) {
+              Write-Error "User creation failed"
+              exit 1
+          }
 
-            New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
-            Add-LocalGroupMember -Group "Administrators" -Member "RDP"
-            Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
-          
-            echo "RDP_CREDS=User: RDP | Password: $password" >> $env:GITHUB_ENV
-          
-            if (-not (Get-LocalUser -Name "RDP")) {
-                Write-Error "User creation failed"
-                exit 1
-            }
 
       - name: Install Tailscale
         run: |
